name: Check API docs
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    container: alpine:edge
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    env:
      MKAPI_BRANCHES: 2.0 2.1
      MKAPI_TAGS: 2.0 2.1
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |-
          apk add doxygen git python3 py3-pip
          pip3 install --break-system-packages jinja2

      - name: Build API docs
        run: |-
          ./mkapi
